name: weather_app
description: A Weather Application with API
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0-85.0.dev <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  anim_search_bar: ^2.0.3
  intl: ^0.17.0
  http: ^0.13.5
  get: ^4.6.5
  geolocator: ^9.0.2
  flutter_launcher_icons: ^0.11.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  dependency_validator:


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon2.png"

flutter:
  uses-material-design: true

  assets:
    - assets/icons/wind.png
    - assets/icons/cloud.png
    - assets/icons/humidity.png
    - assets/icons/minTemp.png
    - assets/icons/maxTemp.png
    - assets/icons/sunset.png
    - assets/icons/sunrise.png
    - assets/images/weather/01d.png
    - assets/images/weather/01n.png
    - assets/images/weather/02d.png
    - assets/images/weather/02n.png
    - assets/images/weather/03d.png
    - assets/images/weather/03n.png
    - assets/images/weather/04d.png
    - assets/images/weather/04n.png
    - assets/images/weather/09d.png
    - assets/images/weather/09n.png
    - assets/images/weather/10d.png
    - assets/images/weather/10n.png
    - assets/images/weather/11d.png
    - assets/images/weather/11n.png
    - assets/images/weather/13d.png
    - assets/images/weather/13n.png
    - assets/images/weather/50d.png
    - assets/images/weather/50n.png

